//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 SkyEyes.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SKYEYES_FORM                101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SkyEyesTYPE                 130
#define ID_VIEW_OUTPUTWND               149
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_PARA1                       310
#define IDD_PARA2                       311
#define IDD_PARA3                       312
#define IDD_NewProject                  313
#define IDD_PARA4                       314
#define IDC_TAB                         1000
#define IDC_EDIT_minDisp                1001
#define IDC_e7ObjDist                   1002
#define IDC_EDIT_SADWinSiz              1003
#define IDC_EDIT_textThres              1004
#define IDC_SLIDER1                     1005
#define IDC_SLIDER_minDisp              1005
#define IDC_SLIDER3                     1006
#define IDC_STATICL                     1006
#define IDC_SLIDER_SADWinSiz            1006
#define IDC_SLIDER4                     1007
#define IDC_STATICR                     1007
#define IDC_SLIDER_textThres            1007
#define IDC_SLIDER5                     1008
#define IDC_BoardWidth                  1008
#define IDC_SLIDER_preFiltCap           1008
#define IDC_BoardHeight                 1009
#define IDC_EDIT_preFiltCap             1009
#define IDC_SLIDER6                     1010
#define IDC_SquareSize                  1010
#define IDC_SLIDER_uniqRatio            1010
#define IDC_nBoards                     1011
#define IDC_EDIT_uniqRatio              1011
#define IDC_SLIDER7                     1012
#define IDC_SLIDER_speckRange           1012
#define IDC_SLIDER2                     1013
#define IDC_SLIDER_maxDisp              1013
#define IDC_EDIT_speckRange             1014
#define IDC_SLIDER8                     1015
#define IDC_SLIDER_speckWinSiz          1015
#define IDC_EDIT_speckWinSiz            1016
#define IDC_SLIDER9                     1017
#define IDC_SLIDER_disp12MaxDiff        1017
#define IDC_EDIT_disp12MaxDiff          1018
#define IDC_EDIT_maxDisp                1019
#define IDC_PicLfCam                    1020
#define IDC_PicRiCam                    1021
#define IDC_PicSynImg                   1022
#define IDC_EDIT_ProjectName            1023
#define IDC_CP4CamList_L                1024
#define IDC_CP4CamList_R                1025
#define IDC_CP4Resolution               1026
#define IDC_CP4MethodList               1031
#define IDC_RAD_ToHSV                   1032
#define IDC_RAD_ToLab                   1033
#define IDC_RAD_ToHLS                   1034
#define IDC_RAD_ToLuv                   1035
#define IDC_RAD_ToYCrCb                 1036
#define IDC_RAD_ToXYZ                   1037
#define IDC_Alpha                       1038
#define IDC_CHK_FPP                     1039
#define IDC_CHK_UIG                     1040
#define IDC_CHK_FAR                     1041
#define IDC_CHK_SFL                     1042
#define IDC_CHK_FI                      1043
#define IDC_RADIO1                      1048
#define IDC_RAD_GrayDisp                1049
#define IDC_RAD_TopDownView             1050
#define IDC_RAD_SideView                1051
#define IDC_CP1CamList_L                1052
#define IDC_CP1CamList_R                1053
#define IDC_CP1Resolution               1054
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON7                      32779
#define ID_RefreshCam                   32779
#define ID_BUTTON8                      32780
#define ID_Photograph                   32780
#define IDC_BN_DefaultCamCalibParam     32781
#define IDC_BN_DeleteCamCalibParam      32782
#define IDC_BNDETECTAG                  32783
#define IDC_BN2StereoCalib              32784
#define IDC_RAD_BOUGUET                 32786
#define IDC_RAD_BM                      32787
#define IDC_RAD_SGBM                    32788
#define IDC_BN_StereoDefParam           32793
#define IDC_BN_StereoDeleteParam        32794
#define IDC_BNGIVEDISP                  32795
#define IDC_BN_CompDisp                 32796
#define ID_BUTTON12                     32797
#define IDC_BN_MOUSEON                  32797
#define ID_CHECK6                       32798
#define ID_CHECK7                       32799
#define ID_BUTTON13                     32800
#define IDC_FACEDETECT                  32801
#define IDC_ONLYDISP                    32802
#define IDC_SGBMTEST                    32803
#define IDC_RAD_HARTLEY                 32804
#define ID_Menu                         32805
#define ID_32806                        32806
#define ID_NewProject                   32807
#define ID_OpenPath                     32808
#define ID_HelpDoc                      32809
#define ID_TESTCALIB                    32810
#define ID_STOPCALIB                    32811
#define ID_OpenProject                  32812
#define ID_BUTTON4                      32813
#define ID_CloseProject                 32814
#define IDC_BN1RunCam                   32816
#define IDC_BN2StopCam                  32817
#define ID_BUTTON9                      32818
#define ID_CHK_Calculate                32820
#define ID_CHK_YML                      32821
#define ID_CalibFromYML                 32822

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
